.ig
Copyright (c) 2016, Carsten Kunze <carsten.kunze@arcor.de>

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
..
.Dd November 26, 2016
.Dt VDDIFF 1
.Sh NAME
.Nm vddiff
.Nd text terminal directory diff tool
.Sh SYNOPSYS
.Nm
.Op Fl u Op Ar "RC file"
.Op Fl BbcdEefgIiklmnoqrVy
.Op Fl F Ar file name pattern
.Op Fl G Ar file content pattern
.Op Fl t Ar diff_tool
.Op Fl v Ar view_tool
.Oo
.Ar directory_1
.Op Ar directory_2
.Oc
.Sh DESCRIPTION
.Nm
stands for
.Dq Vim Directory DIFF .
It is a simple text terminal directory diff tool using
.Xr vim 1
for the actual diff operation.
(If vim is not installed,
.Dq Li diff Ar file_1 Ar file_2 Li | less
is used instead.
Other diff tools can be configured as well.)
A file browser displays the names found in the directories
given on the command line.
Only plain files and symbolic links are compared.
Unless option
.Fl r
is used,
directories are not compared before they are entered.
.Pp
Compressed files are automatically decompressed into
a temporary directory before the diff tool is started.
These files are detected by their file name extension,
the file contents are not checked.
Currently the following file name extensions are
supported:
.Li bz2 ,
.Li gz ,
.Li tar ,
.Li tbz ,
.Li tgz ,
and
.Li zip .
.Pp
If
.Nm
is started with only one or no argument
it behaves like a simple single directory view
file browser (a mode called
.Sy bmode
whereas the normal mode is called
.Sy diff mode ) .
By use of marks files can be compared in bmode,
but comparing directories is not possible.
If less than two arguments are used in two-column mode
kind of a file manager mode (called
.Sy fmode )
is started.
This mode does not support global marks but allows
comparison of directories.
All
.Nm
modes are explained in section
.Sx VDDIFF MODES .
.Pp
Symbols are printed in two columns before the names
which have the following meaning:
.Pp
First column (or middle bar in two-column mode): Difference type
.Bl -column -offset indent ".Sq Li !"
.It So Li " " Sc Ta "Directory, equal files or different file types"
.It So Li ! Sc Ta "Different files or links (or directories with option" Fl r )
.It So Li < Sc Ta "Files found in first directory only"
.It So Li > Sc Ta "Files found in second directory only"
.It So Li = Sc Ta "Files have same i-node"
.It So Li - Sc Ta Error
.It So Li X Sc Ta "Two-column mode: Different file type"
.El
.Pp
Second column (or first column in two-column mode and
.Sy bmode ) :
File type
.Bl -column -offset indent ".Sq Li !"
.It So Li /   Sc Ta Directory
.It So Li " " Sc Ta "Plain file"
.It So Li @   Sc Ta "Symbolic link"
.It So Li c   Sc Ta "Character device"
.It So Li b   Sc Ta "Block device"
.It So Li =   Sc Ta Socket
.It So Li |   Sc Ta FIFO
.It So Li ?   Sc Ta "Unknown file type"
.It So Li !   Sc Ta "Different file type"
.El
.Sh OPTIONS
.Bl -tag -width 12n
.It Fl b
Disable color.
.It Fl c
Show only directories which exist in both trees
and really different files.
.It Fl d
Use
.Dq Li diff $1 $2 | less
as diff tool.
(If a specific diff tool (other than
.Li vim -d )
should be used in general, it is recommended
to configure it with the RC file option
.Sy difftool ,
see section
.Sx CONFIGURATION FILE ~/.vddiffrc
below.)
.It Fl E
Use extended regular expressions.
.It Fl e
Use basic regular expressions.
.It Fl F Ar pattern
Display only file names which match
.Ar pattern ,
which is normally a case ignoring basic regular expression.
With
.Fl E
extended regular expressions are enabled,
with
.Fl I
case-sensitive matching is used.
The pattern match is only applied to non-directories.
To display only directories which contain matching
files add option
.Fl r
(command
.Do Nm
.Fl rF Ar pattern Ar directory Dc
works in bmode somehow similar to
.Dq Nm find Ar directory Fl name Ar pattern ) .
Key
.Sq Li E
toggles display of all files and directories or
matching files only.
.It Fl f
Normally directories are displayed on top.
With this option files are displayed first.
.It Fl G Ar pattern
Display only files which contain
.Ar pattern
(which is normally a case ignoring basic regular expression).
With
.Fl E
extended regular expressions are enabled,
with
.Fl I
case-sensitive matching is used.
The pattern match is only applied to regular files.
To display only directories which contain matching
files add option
.Fl r
(command
.Do Nm
.Fl rG Ar pattern Ar directory Dc
works in bmode somehow similar to
.Dq Nm grep Fl r Ar pattern Ar directory ) .
Key
.Sq Li E
toggles display of all files and directories or
matching files only.
Option
.Fl G
can be combined with option
.Fl F .
For example
.Pp
.Dl vddiff \-rF '\(rs.[1-9]$' \-G '/usr'
.Pp
finds all manpage source files which contain
absolut path names.
Option
.Fl G
can be used multiple times, in this case
.Sy all
.Ar pattern Ns No s
are required to match.
This differs from
.Xr grep 1 ,
where at least one pattern needs to match.
But this can also be expressed as
.Pp
.D1 Fl EG Li ' Ns Ao Ar pattern1 Ac Ns Li | Ns Ao Ar pattern1 Ac Ns Li ' .
.Pp
For example
.Pp
.Dl vddiff \-rF '\(rs.[1-9]$' \-IG '^\.Dd' \-EG '/(usr|etc|var)'
.Pp
finds all manpage source files in
.Fl mdoc
format which contain absolut path names.
Options
.Fl E , e , I ,
and
.Fl i
can be used again before each
.Fl G
option to specify the kind of regular expression
and the case sensitivity for the
.Ar pattern .
.It Fl g
Use
.Nm gvim
as diff and view tool.
.It Fl I
Use case-sensitive pattern match.
.It Fl i
Use case-insensitive pattern match.
.It Fl k
Use
.Nm tkdiff
as diff tool.
.It Fl l
Follow symbolic links.
.It Fl m
Normally directories are displayed on top.
This is disabled with this option.
.It Fl n
This option suppresses the display of equal files.
.It Fl o
Hide files which are on one side only.
.It Fl q
Debug option:
Print differing files and exit (similar to
.Dq Li diff \-q ,
but output is unsorted).
.It Fl r
Recursively scan directories to detect differences in subdirectories.
This allows to mark directories which contain differences.
It increases the start time (due to disk I/O) since
the full file tree is compared at begin.
To only show different directories this option needs to be
combined with
.Fl c .
Pressing key
.Sq c
enables to view all files in this mode.
.It Fl t Ar diff_tool
Specify diff tool on the command line.
The filenames to compare are appended to the given string.
To include them into the string the symbolic names
.Dq Li $1
and
.Dq Li $2
can be used (in any order), where
.Dq Li $1
refers to the first and
.Dq Li $2
to the second file.
Note that the shell may require quoting as in
.Pp
.Dl \-t \(dqdiff \(rs$1 \(rs$2 | vim \-R \-\(dq
.It Fl u Op Ar filename
Skip reading the initialization file at start-up.
If
.Fl u
is used, it must be the very first option.
Other used options need to begin with
.Sq Fl
again.
If an optional
.Ar filename
is supplied, this file is read instead of the default
initialization file
.Pa ~/.vddiffrc .
.Ar filename
needs to be separated with white space from
.Fl u .
.It Fl V
Print version and exit.
.It Fl v Ar view_tool
Specify view tool on the command line.
The filenames is appended to the given string.
To include it into the string the symbolic name
.Dq Li $1
can be embedded which is expanded to the filename.
.It Fl y
Start in two-column mode.
This is currently only supported if two arguments are given.
.El
.Sh INTERACTIVE COMMANDS
.Bl -tag -width 12n
.It Sq Li Q
Quit
.Nm .
.It So Li h Sc or Sq Li \&?
Display help.
Help mode is left with
.Sq Li q .
Keys
.Aq Cm DOWN ,
.Aq Cm UP ,
.Aq Cm PAGE-DOWN ,
and
.Aq Cm PAGE-UP
are used for scrolling in help mode.
.It Aq Cm CTRL-l
Refresh display.
This may be necessary after another application
had output text into the curses controlled display.
.It Ao Cm UP Ac , So Li k Sc or Sq Li \-
Move cursor line up.
.It Ao Cm DOWN Ac , So Li j Sc or Sq Li +
Move cursor line down.
.It Aq Cm LEFT
Leave directory (one directory up).
.It Ao Cm RIGHT Ac , Ao Cm ENTER Ac , or double click
View file, enter directory or start diff tool.
Compressed files and directories
are unpacked before the view or diff tool is started.
.Pp
If a file is marked (with
.Sq Li m ) ,
only
.Ao Cm RIGHT Ac and double click
can be used to normally view files or enter directories.
.Aq Cm ENTER
starts a diff between the marked file
and the selected file or directory.
.It Ao Cm PAGE-UP Ac or Aq Cm BACKSPACE
Scroll one screen up.
.It Ao Cm PAGE-DOWN Ac or Aq Cm SPACE
Scroll one screen down.
.It Ao Cm HOME Ac or Sq Li 1G
Go to first file.
.It Ao Cm END Ac or Sq Li G
Go to last file.
.It So Li | Sc Ns Aq Cm LEFT
In two-column mode:
Enlarge right column by 10 characters.
.It So Li | Sc Ns Aq Cm RIGHT
In two-column mode:
Enlarge left column by 10 characters.
.It Dq Li |=
In two-column mode:
Make column widths equal.
.It Aq Cm CTRL-w
In diff mode:
Toggle two-column mode.
.It Sq Li /
Search file in list by typing the begin of the filename.
Searching is normally done case-insensitive.
Set option
.Cm noic
to change this.
Search mode is left when a file is selected (with
.Aq Cm RIGHT
or
.Aq Cm ENTER ) .
.It Dq Li //
Search with a basic regular expression for a filename.
This can be configured with options
.Cm noic
(don't ignore case),
.Cm magic
(use extended regular expressions), and
.Cm nows
(don't wrap around when search hits top or bottom
of the file list).
Regex search mode is not left until
.Sq Li r
is pressed.
.Pp
Previously entered search patterns are saved in a history,
which can be accessed with the
.Aq Cm UP
and
.Aq Cm DOWN
keys.
.It Dq Li \&Sd
Sort files with directories on top.
.It Dq Li \&Sm
Sort files by name only (ignoring file type).
.It Dq Li \&SS
Sort files by size with directories on top,
smallest file first.
.It Dq Li \&St
Sort files by modification time only,
oldest first (ignoring file type).
.It Sq Li H
Put cursor to top line.
.It Sq Li M
Put cursor on middle line.
.It Sq Li L
Put cursor on bottom line.
.It Dq Li z Ns Aq Cm ENTER
Put selected file to top.
.It Dq Li z.
Center selected file.
.It Dq Li z-
Put selected file to bottom.
.It Aq Cm CTRL-e
Scroll one line down.
.It Aq Cm CTRL-y
Scroll one line up.
.It Aq Cm CTRL-d
Scroll half screen down.
.It Aq Cm CTRL-u
Scroll half screen up.
.It So Li ! Sc or Sq Li n
Toggle display of equal files.
.It Sq Li c
Toggle display of all files or
only directories which exist in both trees
and really different files.
.It Sq Li &
Toggle display of files which are on one side only.
.It Sq Li F
Toggle following symbolic links.
.It Sq Li E
Toggle file name
.Pq Fl F
.ig
or file content
.Pq Fl G
..
filter.
.It Sq Li p
Show current relative work directory.
.It Sq Li a
Show command line directory arguments.
.It Sq Li f
Show full path.
.It Oo Ar n Oc Ns Dq Li <<
Copy from second to first tree.
If
.Ar n
as a number between 2 and 9 (inclusive) is given,
.Ar n
files starting from the current selection are copied.
.Pp
If symbolic links in source and target are followed
or not is toggled with
.Sq Li F .
Following links is signaled with letter F
on the right side of the status line.
.Pp
When links are not followed the target file or directory
is removed before the copy operation starts.
This sets owner and group of the target file
to the effective user and group of the
.Nm
process.
To keep e.g. owner and group setting switch to follow
links (with
.Sq Li F ) .
In this case files are only deleted
when they are not writeable.
.It Oo Ar n Oc Ns Dq Li >>
Copy from first to second tree.
.It Dq Li \(ga<<
Copy all files between the cursor and the local mark (inclusive)
from second to first tree.
.It Dq Li \(ga>>
Copy all files between the cursor and the local mark (inclusive)
from first to second tree.
.It Oo Ar n Oc Ns Dq Li dd
Delete file or directory, which must be present in one tree only.
(Does not follow symbolic links.)
.Nm
does not warn if a directory to delete is not empty.
If
.Ar n
as a number between 2 and 9 (inclusive) is given,
.Ar n
files starting from the current selection are deleted.
.It Oo Ar n Oc Ns Dq Li dl
Delete file or directory in first tree.
(Does not follow symbolic links.)
.It Oo Ar n Oc Ns Dq Li dr
Delete file or directory in second tree.
(Does not follow symbolic links.)
.It Dq Li \(gadd
Delete all files between the cursor and the local mark (inclusive),
which must be present in one tree only.
(Does not follow symbolic links.)
.It Dq Li \(gadl
Delete all files between the cursor and the local mark (inclusive)
in first tree.
(Does not follow symbolic links.)
.It Dq Li \(gadr
Delete all files between the cursor and the local mark (inclusive)
in second tree.
(Does not follow symbolic links.)
.It Dq Li en
Rename file, which must be present in one tree only.
.It Dq Li eln
Rename file in first tree.
.It Dq Li ern
Rename file in second tree.
.It Oo Ar n Oc Ns Dq Li ep
Change permissions of file, which must be present in one tree only.
If following symbolic links is not enabled
the command is ignored for symbolic links.
If decimal digit
.Ar n
is given, the mode of
.Ar n
files starting from the current selection is set.
.It Oo Ar n Oc Ns Dq Li elp
Change permissions of file in first tree.
.It Oo Ar n Oc Ns Dq Li erp
Change permissions of file in second tree.
.It Dq Li \(gaep
Change permissions of
all files between the cursor and the local mark (inclusive),
which must be present in one tree only.
.It Dq Li \(gaelp
Change permissions of
all files between the cursor and the local mark (inclusive)
in first tree.
.It Dq Li \(gaerp
Change permissions of
all files between the cursor and the local mark (inclusive)
in second tree.
.It Oo Ar n Oc Ns Dq Li eu
Change owner of file, which must be present in one tree only.
If following symbolic links is not enabled
the command is ignored for symbolic links.
Previously entered user names are saved in a history,
which can be accessed with the
.Aq Cm UP
and
.Aq Cm DOWN
keys.
If decimal digit
.Ar n
is given, the owner of
.Ar n
files starting from the current selection is set.
.It Oo Ar n Oc Ns Dq Li elu
Change owner of file in first tree.
.It Oo Ar n Oc Ns Dq Li eru
Change owner of file in second tree.
.It Dq Li \(gaeu
Change owner of
all files between the cursor and the local mark (inclusive)
which must be present in one tree only.
.It Dq Li \(gaelu
Change owner of
all files between the cursor and the local mark (inclusive)
in first tree.
.It Dq Li \(gaeru
Change owner of
all files between the cursor and the local mark (inclusive),
in second tree.
.It Oo Ar n Oc Ns Dq Li eg
Change group of file, which must be present in one tree only.
If following symbolic links is not enabled
the command is ignored for symbolic links.
Previously entered group names are saved in a history,
which can be accessed with the
.Aq Cm UP
and
.Aq Cm DOWN
keys.
If decimal digit
.Ar n
is given, the group of
.Ar n
files starting from the current selection is set.
.It Oo Ar n Oc Ns Dq Li elg
Change group of file in first tree.
.It Oo Ar n Oc Ns Dq Li erg
Change group of file in second tree.
.It Dq Li \(gaeg
Change group of
all files between the cursor and the local mark (inclusive)
which must be present in one tree only.
.It Dq Li \(gaelg
Change group of
all files between the cursor and the local mark (inclusive)
in first tree.
.It Dq Li \(gaerg
Change group of
all files between the cursor and the local mark (inclusive),
in second tree.
.It Sq Li P
Create directory
.Sy ( bmode
and
.Sy fmode
only).
.It Dq Li Pl
Create directory in left tree.
.It Dq Li Pr
Create directory in right tree.
.It Sq Li m
Mark file or directory.
This can be used to compare files or directories
which had been renamed or compressed in one file tree.
.Pp
Marks are defined globally and can be used to compare
files from different file hierarchy depths.
They can only be undefined with the
.Sq Li r
key (or redefined with the
.Sq Li m
key).
As long as the current directory is not left,
the marked file is highlighted with either a bold font
or a blue background.
.Pp
If a mark is set, only
.Aq Cm RIGHT
and double click
can be used to normally view files or change to other directories.
.Aq Cm ENTER
startes a diff between the marked and the selected file
or directory.
.It Sq Li r
Remove mark, edit line, or regex search.
.It Sq Li b
Test for binary difference between selected and marked file.
Compressed files are unpacked but compressed archive files
are compared directly.
.begin_comment
.Pp
Handling of compressed files is implemented redundant
and should be tested separately.
.end_comment
.It Sq Li y
Copy file path(s) to edit line.
If a
.Sq Li $
command is entered later, this file path can be used
to build a
.Xr sh 1
command.
.It Sq Li Y
Copy file paths to edit line in reverse order.
.It Sq Li $
Enter shell command.
If paths had been copied to the edit line before using the
.Sq Li y
or
.Sq Li Y
command, the shell command can be prepended by pressing
.Aq Cm HOME
and then entering the command.
Predefined strings can be inserted by pressing a
function key.
The work directory is the directory where
.Nm
had been started.
(In
.Sy bmode
the work directory is always the current view directory.)
Each entered command is saved in a history.
The keys
.Aq Cm UP
and
.Aq Cm DOWN
fetch other history entries.
The shell to be used (default
.Dq Li sh )
can be configured with the
.Sy sh
option.
.It Oo Ar n Ns Li | Ns Cm \(ga Oc Ns Ao Cm F1 Ac \(en Aq Cm F12
Define string which can be inserted later with this function key
when entering a
.Xr sh
command using
.Sq Li $ .
This string is usually the name of a UNIX tool.
Regularly used strings can be set using the RC file
.Cm fkey
command.
.Pp
If the string begins with a
.Sq Li $
followed by at least one space
.Pq Sq Li " "
it is treated as shell command itself, which is
applied to a selected file(s).
If that function key is pressed later, a dialog opens
to ask if the command should be executed or the function
key should be redefined.
The filename is appended to the saved string.
To embed it,
.Dq Li $1
and
.Dq Li $2
can be used, as in
.Dq Li "$ nroff $1 | less" .
.Pp
If
.Ar n
as a number between 2 and 9 (inclusive) is given,
the command is applied to
.Ar n
files starting from the current selection.
If
.Sq Li \(ga
is prepended instead, the command is applied to
all files between the cursor and the local mark (inclusive).
.Pp
If the string starts with
.Sq Li \&!
instead of
.Sq Li $ ,
.Aq Cm ENTER
must be pressed after running the command.
This allows to check the command's output.
.Pp
For strings starting with
.Sq Li $
or
.Sq Li \&!
the user has to confirm the command execution.
If the string starts with
.Sq Li #
instead the command is started immediately.
.Pp
To save a command for a function key which does not take
the selected filename as argument, add a space followed
by an octothorpe
.Pq Dq Li " #"
at the end of the string.
.Pp
If no diff tool which supports merging is available,
files can be merged manually by defining two function keys
for editing the left and right side file with
.Dq Li "$ vi $1"
and
.Dq Li "$ vi $2" .
.It Sq Li l
List strings which had been defined for a function key.
.It Sq Li u
Update file list.
.It Sq Li s
Open shell in current directory.
The shell to open can be set with the
.Sy shell
option, else it is read from the user's entry in
.Pa /etc/passwd .
.It Dq Li sl
Open shell in left directory tree.
.It Dq Li sr
Open shell in right directory tree.
.It Sq Li o
Open file (instead of diff tool).
.It Dq Li ol
Open left file or directory.
Plain files are opened with
.Xr less 1
by default.
If no diff tool which supports merging is available,
files can be merged manually opening them with
.Dq Li ol
or
.Dq Li or
and then pressing
.Sq Li v
in
.Li less
which opens
.Li vi .
.It Dq Li or
Open right file or directory.
.It Sq Li v
View raw file contents.
.It Dq Li vl
View raw left file contents.
.It Dq Li vr
View raw right file contents.
.It Sq Li \&:
Enter configuration option.
Entering
.Cm set
displays the current setting of the changable options.
Currently the options
.Po Cm no Pc Ns Cm ic ,
.Po Cm no Pc Ns Cm magic ,
and
.Po Cm no Pc Ns Cm ws
are supported.
.Pp
Previously entered options are saved in a history,
which can be accessed with the
.Aq Cm UP
and
.Aq Cm DOWN
keys.
.It Sq Li =
In
.Sy fmode :
Set path of active column to path of the other column.
.It Sq Li W
Toggle to always wait for <ENTER> after running an external tool.
This can be useful for debugging purposes.
.El
.Sh CONFIGURATION FILE ~/.vddiffrc
Permanent non-default options can be set in the file
.Pa ~/.vddiffrc .
The elements in this file may be separated with
spaces, tabs or line breaks.
Line breaks are not required, everything can be written
into one long line.
Also spaces or tabs are not required (outside quoted strings),
when every element is on it's own line.
Everything following a
.Sq Li #
(outside quoted strings)
to the end of the line is a comment.
.Bl -tag -width 12n
.It Li twocolumn
Start in two-column mode.
This is currently only supported if two arguments are given.
.It Li difftool Ar string
Configure
.Ar string
as diff tool.
If
.Ar string
contains spaces it needs to be quoted with
.Sq Li \(dq
at begin and end.
The two filenames are appended to this string.
If the filenames need to be before a pipe symbol
.Pq Sq Li | ,
the symbols
.Dq Li $1
and
.Dq Li $2
can be embedded into
.Ar string
(in any order).
These symbols are expanded to the respective filename.
.Pp
Other possible diff tools are
.Xr colordiff 1 ,
.Xr mgdiff 1 ,
or
.Xr tkxcd 1 .
.It Li difftool bg Ar string
Start
.Ar string
as a background process (don't block
.Nm
while executing
.Ar string ) .
.Cm bg
is ignored if one of the files to be compared is compressed.
Since they are decompressed into a temporary directory
which is removed after starting the diff tool,
the file may be removed before the tool reads it.
.It Li viewtool Ar string
Configure
.Ar string
as view tool.
If
.Ar string
contains spaces it needs to be quoted with
.Sq Li \(dq
at begin and end.
The filename is appended to this string.
If the filename need to be before a pipe symbol
.Pq Sq Li |
the symbol
.Dq Li $1
can be embedded into
.Ar string ,
which is expanded to the filename.
.It Li viewtool bg Ar string
Start
.Ar string
as a background process.
.Cm bg
is ignored if the file to be viewed is compressed.
Since it is decompressed into a temporary directory
which is removed after starting the view tool,
the file may be removed before the tool reads it.
For example
.Pp
.Dl viewtool bg \(dqxterm -e less\(dq
.Pp
displayes every file to view in a separate window while not
blocking the file browser.
.It Li ext Ar extension Ar string
Configure view tool
.Ar string
for filenames ending with
.Dq Li "." Ns Ar extension .
.Ar extension
is compared case-insensitive.
If
.Ar extension
is an integer number it needs to be enclosed
in double quotes
.Pq Sq \(dq
as in
.Pp
.Dl ext \(dq1\(dq \(dqtbl $1 | neqn | nroff \-mandoc | less\(dq
.Pp
because the parser expects a string (and not a number)
after the keyword
.Li ext .
.It Li ext Ar extension Li bg Ar string
Start
.Ar string
as a background process.
.It Li alias Ar name Ar string
If a pipe of tools (like the nroff pipe above)
or a command with options (like e.g.
.Dq Li mplayer \-idx \-\-
should be applied to many file types,
an alias
.Ar name
can be defined for such a
.Ar string .
The
.Sy ext
command can then use this alias
.Ar name
instead the full command
.Ar string ,
for example
.Bd -literal -offset indent
alias mandoc  "tbl $1 | neqn | nroff -mandoc | less"
alias mplayer "mplayer -idx --"

ext "1" mandoc
ext "2" mandoc
ext "3" mandoc

ext mts mplayer
ext ts  mplayer
.Ed
.Pp
It is also possible to use an alias for defining another alias:
.Bd -literal -offset indent
alias mplayer "mplayer -idx --"
alias audio mplayer

ext mpg mplayer
ext mp3 audio
.Ed
.It Li skipext Ar extension
When checking a filename extension skip
.Ar extension
at the end of the filename.
E.g.
.Pp
.Dl skipext old
.Pp
would remove
.Dq Li .old
from the end of each filename before checking the
extension.
.It Li fkey Ar number Ar string
Define
.Ar string
which can be inserted later with this function key
when entering a sh command using
.Sq Li $ .
This string is usually the name of a UNIX tool.
.Ar number
must be between 1 and 12 (inclusive).
.Pp
If
.Ar string
begins with a
.Sq Li $
followed by at least one space (the string needs to be
enclosed in double quotes in this case),
it defines a shell command to be executed
for the selected file
when pressing the function key.
.Pp
If
.Ar string
starts with
.Sq Li \&!
instead of
.Sq Li $ ,
.Aq Cm ENTER
must be pressed after running the command.
This allows to check the command's output.
.Pp
To save a command for a function key which does not take
the selected filename as argument, add a space followed
by an octothorpe
.Pq Dq Li " #"
at the end of the string.
.It Li mono
Disable colors.
.It Li followlinks
Follow symbolic links.
.It Li noequal
Display differences only, hide equal files.
.It Li real_diff
Show only directories which exist in both trees
and really different files.
.It Li recursive
Recursively scan file tree to detect and mark
directories which contain differences.
This increases the start time.
To show only directories with differences
additionally set option
.Li real_diff .
To view all files when in this mode key
.Sq c
can be used.
.It Li noic
Searching for a filename with
.Sq Li /
or
.Dq Li //
is normally done case-insensitive.
Case-sensitive search can be configured with this option.
.It Li magic
For searching with
.Dq Li //
normally basic regular expressions are used.
Use of extended regular expressions is configured
with this option.
.It Li nows
Searching for a filename with
.Dq Li //
normally wraps around top and bottom of the file list.
This behaviour is disabled with this option.
.It Li filesfirst
Display directories at the end instead on top.
.It Li mixed
Display files and directories mixed.
.It Li dir_color Ar integer
Set color for directories.
Default is 3 (yellow).
.It Li diff_color Ar integer
Set color for different files.
Default is 1 (red).
.It Li link_color Ar integer
Set color for symbolic links.
Default is 5 (magenta).
.It Li left_color Ar integer
Set color for files found in first directory only.
Default is 6 (cyan).
.It Li right_color Ar integer
Set color for files found in second directory only.
Default is 2 (green).
.It Li unknown_color Ar integer
Set color for unknown file types.
Default is 4 (blue).
.It Li normal_color Ar integer
Set color for normal text.
Default is 7 (white).
.It Li bg_color Ar integer
Set background color.
Default is 0 (black).
.It Li cursor_color Ar foreground Ar background
Set the cursor color.
.Ar foreground
and
.Ar background
must be given as integers.
Default is 0 7 (black on white).
.It Li mark_color Ar foreground Ar background
Set color for marks.
.Ar foreground
and
.Ar background
must be given as integers.
Default is 7 4 (white on blue).
.It Li error_color Ar foreground Ar background
Set color for diff errors.
.Ar foreground
and
.Ar background
must be given as integers.
Default is 7 1 (white on red).
.It Li histsize Ar integer
Set history size to
.Ar integer .
Default is 100.
A size less than 2 disables the history
(at least the current command line and one previous
entry need to be saved to use this feature).
.It Li scale
Show file size in human-readable format.
.It Li shell Ar string
Set shell for the
.Sq Li s ,
.Dq Li sl
and
.Dq Li sr
command.
Default is the user's login shell.
.Ar string
may be a full path or just the shell name.
In the latter case
.Li $PATH
is searched to determine the full path.
.It Li sh Ar string
Set shell for the
.Sq Li $
and function key commands,
.Li .gz
and
.Xr .bz2
uncompressing
and any use of the shell special characters
.Li | , & , \&; , < , > , \&( , \&) , \(ga , \(rs , \(dq , \(aq , \&[ , # ,
and
.Li ~ .
Default is
.Dq Li sh .
.Ar string
may be a full path or just the shell name.
In the latter case
.Li $PATH
is searched to determine the full path.
.El
.Sh VDDIFF MODES
.Ss Diff mode
Diff mode is entered when two arguments are used.
Key
.Aq Cm CTRL-w
switches to two-column diff mode,
key
.Sq Li #
switches to fmode.
.Ss Two-column diff mode
Two-column diff mode is equal to diff mode
except for a different data presentation.
Key
.Aq Cm CTRL-w
switches to single-column diff mode,
key
.Sq Li #
switches to fmode.
.Ss Bmode (browse mode)
Bmode is a simply file browser mode.
It allows file comparison by use or marks,
but directory comparison is not possible.
It is not possible to switch from any mode to
or to any mode from bmode.
.Ss Fmode (file manager mode)
Fmode is a simple two-column file manager mode.
It allows comparison of files and directories
by use of local marks.
This mode does not have global marks.
If a directory is left, an existing mark in this
directory is deleted.
Generally in any mode at most one mark is supported.
If a mark is defined, an existing mark (in either column)
is deleted.
A compare of a marked directory (or archive)
with a directory (or archive)
switches to two-column diff mode.
.Sh FILES
.Bl -tag -width ~/.vddiffrc -compact
.It Pa ~/.vddiffrc
Read on start-up to set non-default options.
.El
.\".Sh BUGS
.\"TODO issue:
.\"Pp
.\"Bl -bullet
.\"It
.\"El
.begin_comment
.Sh Regression test items
.Bl -bullet
.It
Terminal window resize
.El
.end_comment
