.ig
Copyright (c) 2016, Carsten Kunze <carsten.kunze@arcor.de>

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
..
.Dd September 11, 2016
.Dt VDDIFF 1
.Sh NAME
.Nm vddiff
.Nd text terminal directory diff tool
.Sh SYNOPSYS
.Nm
.Op Fl ubcdfgklmnr
.Op Fl t Ar diff_tool
.Ar directory_1
.Ar directory_2
.Sh DESCRIPTION
.Nm
stands for
.Dq vim directory diff .
It is a simple text terminal directory diff tool using
.Xr vim 1
for the actual diff operation.
A file browser displays the names found in the directories
given on the command line.
Only plain files and symbolic links are compared.
Unless option
.Fl r
is used,
directories are not compared before they are entered.
Symbols are printed in two columns before the names
which have the following meaning:
.Pp
First column: Difference type
.Bl -column -offset indent ".Sq Li !"
.It So Li " " Sc Ta "Directory, equal files or different file types"
.It So Li ! Sc Ta "Different files or links (or directories with option" Fl r )
.It So Li < Sc Ta "Files found in first directory only"
.It So Li > Sc Ta "Files found in second directory only"
.It So Li = Sc Ta "Files have same i-node"
.El
.Pp
Second column: File type
.Bl -column -offset indent ".Sq Li !"
.It So Li / Sc Ta Directory
.It So Li " " Sc Ta "Plain file"
.It So Li @ Sc Ta "Symbolic link"
.It So Li ? Sc Ta "Any other file type"
.It So Li ! Sc Ta "Different file type"
.El
.Sh OPTIONS
.Bl -tag
.It Fl b
Disable color.
.It Fl c
Show only directories which exist in both trees
and really different files.
.It Fl d
Use
.Dq Li diff '$1' '$2' | less
as diff tool.
Since the arguments to
.Xr diff 1
is quoted with
.Sq Li \(aq ,
this works only for filenames without
.Sq Li \(aq .
.It Fl f
Normally directories are displayed on top.
With this option files are displayed first.
.It Fl g
Use
.Dq Li gvim
as diff and view tool.
.It Fl k
Use
.Dq Li tkdiff
as diff tool.
.It Fl l
Follow symbolic links.
(Note that the integrated file copy and delete operations
never follow symbolic links.)
.It Fl m
Normally directories are displayed on top.
This is disabled with this option.
.It Fl n
This option suppresses the display of equal files.
.It Fl r
Recursively scan directories to detect differences in subdirectories.
This allows to mark directories which contain differences.
It increases the start time (due to disk I/O) since
the full file tree is compared at begin.
To only show different directories this option needs to be
combined with
.Fl c .
Pressing key
.Sq c
enables to view all files in this mode.
.It Fl t Ar diff_tool
Specify diff tool on the command line.
The filenames to compare are appended to the given string.
To include them into the string the symbolic names
.Dq Li $1
and
.Dq Li $2
can be used (in any order), where
.Dq Li $1
refers to the first and
.Dq Li $2
to the second file.
Note that the shell may require quoting as in
.Pp
.Dl -t \(dqdiff '\(rs$1' '\(rs$2' | vim -R -\(dq
.Pp
Also note the quoting of the filenames itself.
When the symbolic names
.Li $ Ns Ar n
are used,
.Xr system 3
instead of
.Xr execvp 3
is used.
This applies restrictions on the characters used
in filenames.
.It Fl u
Skip reading the initialization file at start-up.
This has only effect if
.Fl u
is the very first option.
It is ignored elsewise.
.It Fl v Ar view_tool
Specify view tool on the command line.
The filenames is appended to the given string.
To include it into the string the symbolic name
.Dq Li $1
can be embedded which is expanded to the filename.
Single quotes
.Pq Sq \(aq
can be put around
.Dq Li $1
to allow filenames with spaces.
.El
.Sh INTERACTIVE COMMANDS
.Bl -tag
.It Sq Li q
Quit.
.It So Li h Sc or Sq Li ?
Display help.
.It Ao Cm UP Ac , So Li k Sc or Sq Li -
Move cursor line up.
.It Ao Cm DOWN Ac , So Li j Sc or Sq Li +
Move cursor line down.
.It Aq Cm LEFT
Leave directory (one directory up).
.It Ao Cm RIGHT Ac or Aq Cm ENTER
Enter directory or start diff tool.
.It Ao Cm PAGE-UP Ac or Aq Cm BACKSPACE
Scroll one screen up.
.It Ao Cm PAGE-DOWN Ac or Aq Cm SPACE
Scroll one screen down.
.It Ao Cm HOME Ac or Sq Li 1G
Go to first file.
.It Ao Cm END Ac or Sq Li G
Go to last file.
.It So Li ! Sc or Sq Li n
Toggle display of equal files.
.It Sq Li c
Toggle display of all files or
only directories which exist in both trees
and really different files.
.It Sq Li p
Show current relative work directory.
.It Sq Li a
Show command line directory arguments.
.It Sq Li f
Show full path.
.It Dq Li <<
Copy from second to first tree.
(Does not follow symbolic links.)
.It Dq Li >>
Copy from first to second tree.
(Does not follow symbolic links.)
.It Dq Li dd
Delete file or directory, which must be present in one tree only.
(Does not follow symbolic links.)
.It Dq Li dl
Delete file or directory in first tree.
(Does not follow symbolic links.)
.It Dq Li dr
Delete file or directory in second tree.
(Does not follow symbolic links.)
.It Dq Li en
Rename file, which must be present in one tree only.
.It Dq Li eln
Rename file in first tree.
.It Dq Li ern
Rename file in second tree.
.It Dq Li ep
Change permissions of file, which must be present in one tree only.
.It Dq Li elp
Change permissions of file in first tree.
.It Dq Li erp
Change permissions of file in second tree.
.It Sq Li m
Mark file or directory.
This can be used to compare files or directories
which had been renamed in one file tree.
.It Sq Li r
Remove edit line or mark.
.It Sq Li y
Copy file path(s) to edit line.
If a
.Sq Li $
command is entered later, this file path can be used
to build a
.Xr sh 1
command.
.It Sq Li Y
Copy file paths to edit line in reverse order.
.It Sq Li $
Enter
.Xr sh 1
command.
If paths had been copied to the edit line before using the
.Sq Li y
or
.Sq Li Y
command, the shell command can be prepended by pressing
.Aq Cm HOME
and then  entering the command.
The work directory is the directory where
.Nm
had been started.
.El
.Sh CONFIGURATION FILE ~/.vddiffrc
Permanent non-default options can be set in the file
.Pa ~/.vddiffrc .
The elements in this file may be separated with
spaces, tabs or line breaks.
Line breaks are not required, everything can be written
into one long line.
Also spaces or tabs are not required (outside quoted strings),
when every element is on it's own line.
Everything following a
.Sq Li #
to the end of the line is a comment.
.Bl -tag
.It Li difftool Ar string
Configure
.Ar string
as diff tool.
If
.Ar string
contains spaces it needs to be quoted with
.Sq Li \(dq
at begin and end.
The two filenames are appended to this string.
If the filenames need to be before a pipe symbol
.Pq Sq Li | ,
the symbols
.Dq Li $1
and
.Dq Li $2
can be embedded into
.Ar string
(in any order).
These symbols are expanded to the respective filename.
Since in this case the command is executed by
.Xr sh 1
instead of
.Xr execvp 3 ,
there are restrictions to the allowed characters
in filenames.
E.g. put
.Li $ Ns Ar n
in single quotes to allow filenames with spaces.
.It Li difftool bg Ar string
Start
.Ar string
as a background process (don't block
.Nm
while executing
.Ar string ) .
.It Li viewtool Ar string
Configure
.Ar string
as view tool.
If
.Ar string
contains spaces it needs to be quoted with
.Sq Li \(dq
at begin and end.
The filename is appended to this string.
If the filename need to be before a pipe symbol
.Pq Sq Li |
the symbol
.Dq Li $1
can be embedded into
.Ar string ,
which is expanded to the filename.
.It Li viewtool bg Ar string
Start
.Ar string
as a background process.
.It Li ext Ar extension Ar string
Configure view tool
.Ar string
for filenames ending with
.Dq Li "." Ns Ar extension .
.Ar extension
is compared case-insensitive.
.It Li ext Ar extension Li bg Ar string
Start
.Ar string
as a background process.
.It Li mono
Disable colors.
.It Li followlinks
Follow symbolic links.
(Note that the integrated file copy and delete operations
never follow symbolic links.)
.It Li noequal
Display differences only, hide equal files.
.It Li real_diff
Show only directories which exist in both trees
and really different files.
.It Li recursive
Recursively scan file tree to detect and mark
directories which contain differences.
This increases the start time.
To show only directories with differences
additinally set option
.Li real_diff .
To view all files when in this mode key
.Sq c
can be used.
.It Li filesfirst
Display directories at the end instead on top.
.It Li mixed
Display files and directories mixed.
.It Li dir_color Ar integer
Set color for directories.
Default is 3 (yellow).
.It Li diff_color Ar integer
Set color for different files.
Default is 1 (red).
.It Li link_color Ar integer
Set color for symbolic links.
Default is 5 (magenta).
.It Li left_color Ar integer
Set color for files found in first directory only.
Default is 6 (cyan).
.It Li right_color Ar integer
Set color for files found in second directory only.
Default is 2 (green).
.It Li unknown_color Ar integer
Set color for unknown file types.
Default is 4 (blue).
.El
.Sh FILES
.Bl -tag -width ~/.vddiffrc -compact
.It Pa ~/.vddiffrc
Read on start-up to set non-default options.
.El
.Sh BUGS
TODO issues:
.Pp
.Bl -bullet
.It
Comparing compressed files.
.It
Executing files with
.So Li x Sc .
.El
